camera_matrix:
- - 909.3394775390625
  - 0.0
  - 641.5870361328125
- - 0.0
  - 909.4758911132812
  - 366.2402038574219
- - 0.0
  - 0.0
  - 1.0
distortion_coefficients:
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
source: Manual
timestamp: '20251115_123426'
